# Generated by Django 2.0 on 2020-06-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0007_appointments_payment_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=50)),
                ('Weight', models.CharField(max_length=50)),
                ('prescribed_medicine', models.CharField(max_length=500)),
                ('blood_group', models.CharField(max_length=50)),
                ('report_message', models.CharField(max_length=500)),
                ('appointment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointments')),
            ],
        ),
    ]
