# Generated by Django 2.0 on 2020-06-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctorbasicdetail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorbasicdetail',
            old_name='deparment',
            new_name='department',
        ),
    ]
