# Generated by Django 2.0 on 2020-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBasicDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
