# Generated by Django 2.0 on 2020-06-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointments_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(default='TO MANAGER', max_length=200),
        ),
    ]
