# Generated by Django 2.0 on 2020-06-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200618_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
