# Generated by Django 2.0 on 2020-06-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointments_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='payment_info',
            field=models.CharField(default='FALSE', max_length=100),
        ),
    ]
